"""Generate mobile rendering assets from the desktop source; no desktop globals."""
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[1]
target = ROOT / 'mobile_web'
(target / 'vendor').mkdir(parents=True, exist_ok=True)
for name in ('marked.min.js', 'katex.min.js', 'katex.min.css', 'highlight.min.js', 'github-dark.min.css', 'raindrop-fx.min.js', 'raindrop-fx.LICENSE'):
    shutil.copy2(ROOT / 'app/static/vendor' / name, target / 'vendor' / name)
shutil.copytree(ROOT / 'app/static/vendor/fonts', target / 'vendor/fonts', dirs_exist_ok=True)
shutil.copy2(ROOT / 'app/static/starfield.js', target / 'shared-background.js')
source = (ROOT / 'app/static/render.js').read_text(encoding='utf-8')
parts = ['// Generated by mobile_server/prepare_assets.py; edit desktop render.js instead.\n']
for name in ('renderLatexInDom', 'renderMarkdown'):
    start = source.index('function ' + name + '(')
    end = source.index('\nfunction ', start + 1)
    parts.append(source[start:end])
result = '\n'.join(parts).replace('container.innerHTML = finalHtml;',
    "container.innerHTML = DOMPurify.sanitize(finalHtml, {USE_PROFILES: {html: true}, FORBID_TAGS: ['img', 'style', 'input', 'form', 'button'], FORBID_ATTR: ['style', 'id', 'name']});")
(target / 'shared-render.js').write_text(result, encoding='utf-8')
print('Mobile shared rendering assets prepared')
